FROM fedora:35

ENV HOME /root
ENV DEBIAN_FRONTEND noninteractive
ENV LC_ALL C.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8
ENV OS fedora
ENV OSVER 35

RUN dnf install -y curl dnf-plugins-core fluxbox gnupg2 net-tools procps python-is-python3 supervisor tar x11vnc xdotool xorg-x11-server-Xvfb && \
    dnf config-manager --add-repo https://dl.winehq.org/wine-builds/fedora/${OSVER}/winehq.repo && \
    dnf install -y winehq-stable && \
    curl -Lf http://winetricks.org/winetricks -o /usr/bin/winetricks && chmod +x /usr/bin/winetricks && \
    dnf update -y && dnf clean all && rm -rf /var/cache/dnf
ADD supervisord.conf /etc/supervisord.conf

ENV WINEPREFIX /root/prefix32
ENV WINEARCH win32
ENV WINEDLLOVERRIDES mscoree,mshtml=
ENV DISPLAY :0

ENV noVNC 1.3.0
ENV websockify 0.10.0

WORKDIR /root/
RUN curl -Lf https://github.com/novnc/noVNC/archive/refs/tags/v${noVNC}.tar.gz | tar -xzv -C /root/ && mv /root/noVNC-${noVNC} /root/novnc && ln -s /root/novnc/vnc_lite.html /root/novnc/index.html && \
    curl -Lf https://github.com/novnc/websockify/archive/refs/tags/v${websockify}.tar.gz | tar -xzv -C /root/ && mv /root/websockify-${websockify} /root/novnc/utils/websockify

EXPOSE 8080

CMD ["/usr/bin/supervisord"]
